file <- c("household_power_consumption.txt")
data_subset <- read.csv.sql(file, header = T, sep=";", sql = "select * from file where (Date == '1/2/2007' OR Date == '2/2/2007')")
data_subset$Date <- as.POSIXlt(paste(as.Date(data_subset$Date,format="%d/%m/%Y"), data_subset$Time, sep=" "))
data_subset$Time <- strptime(data_subset$Time , format = "%H:%M:%S")
png("plot4.png")
par(mfrow=c(2,2))
layout(matrix(c(1,2,3,4),2,2,byrow=TRUE))
yrange<-range(data_subset$Sub_metering_1,data_subset$Sub_metering_2,data_subset$Sub_metering_3)
with(data_subset, plot(Date,Global_active_power,type="l",xlab="", ylab="Global Active Power"))
with(data_subset, plot(Date,Voltage,type="l",xlab="datetime", ylab="Voltage"))
with(data_subset, plot(Date,Sub_metering_1,type="l",xlab="", ylab="Energy sub metering"),ylim=yrange)
par(new=T)
with(data_subset, plot(Date,Sub_metering_2,type="l",xlab="", ylab="Energy sub metering", col=2, axes=F,ylim=yrange))
par(new=T)
with(data_subset, plot(Date,Sub_metering_3,type="l",xlab="", ylab="Energy sub metering", col=4, axes=F,ylim=yrange))
par(new=F)
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), bty="n", lty=c(1,1,1), lwd=c(1,1,1), col=c(1,2,4), cex=0.9)
with(data_subset, plot(Date,Global_reactive_power,type="l",xlab="datetime"))
dev.off()