file <- c("household_power_consumption.txt")
data_subset <- read.csv.sql(file, header = T, sep=";", sql = "select * from file where (Date == '1/2/2007' OR Date == '2/2/2007')")
data_subset$Date <- as.Date(data_subset$Date , format = "%d/%m/%y")
data_subset$Time <- strptime(data_subset$Time , format = "%H:%M:%S")
png("plot1.png")
hist(data_subset$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()